name: OnePlus 13 Kernel Build

on:
  workflow_dispatch:
    inputs:
      CPU:
        description: "分支"
        required: true
        default: 'sm8750'
      FEIL:
        description: "配置文件"
        required: true
        default: 'oneplus_13'
      ANDROID_VERSION:
        description: "安卓版本"
        required: true
        default: 'android15'
      KERNEL_VERSION:
        description: "内核版本"
        required: true
        default: '6.6'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KERNEL_DIR: ${{ github.workspace }}/kernel_workspace

    steps:
    # 保留原始空间优化步骤
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 8192
        temp-reserve-mb: 2048
        remove-dotnet: true
        remove-android: true

    # 修正依赖安装（保持原始项目的依赖要求）
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3 \
          git \
          curl \
          flex \
          bison \
          build-essential \
          libssl-dev \
          libelf-dev \
          dwarves \
          bc \
          ccache \
          rsync \
          aria2

    # 保持原始repo初始化流程
    - name: Initialize repo
      run: |
        mkdir -p $KERNEL_DIR
        cd $KERNEL_DIR
        repo init -u https://github.com/JiuGeFaCai/kernel_manifest.git \
          -b refs/heads/oneplus/${{ inputs.CPU }} \
          -m ${{ inputs.FEIL }}.xml \
          --depth=1
        repo sync -c -j$(nproc --all)

    # 修正SukiSU安装步骤
    - name: Apply SukiSU
      working-directory: $KERNEL_DIR/kernel_platform
      run: |
        curl -sSL https://raw.githubusercontent.com/ShirkNeko/SukiSU-Ultra/main/kernel/setup.sh | bash -s susfs-dev
        cd KernelSU
        KSU_VERSION=$(($(git rev-list --count main) + 10606))
        echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
        sed -i "s/DKSU_VERSION=12800/DKSU_VERSION=${KSU_VERSION}/" kernel/Makefile

    # 保持原始SUSFS补丁流程
    - name: Apply SUSFS patches
      working-directory: $KERNEL_DIR
      run: |
        git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-${{ inputs.ANDROID_VERSION }}-${{ inputs.KERNEL_VERSION }}
        git clone https://github.com/ExmikoN/SukiSU_patch.git
        
        # 原始项目的文件复制方式
        cp -r susfs4ksu/kernel_patches/* kernel_platform/common/
        cp -r SukiSU_patch/other/lz4k/* kernel_platform/common/
        
        cd kernel_platform/common
        patch -p1 < 50_add_susfs_in_gki-*.patch
        patch -p1 < syscall_hooks.patch

    # 恢复原始编译参数设置
    - name: Configure kernel
      working-directory: $KERNEL_DIR/kernel_platform
      run: |
        echo "CONFIG_KSU=y" >> common/arch/arm64/configs/gki_defconfig
        echo "CONFIG_KPM=y" >> common/arch/arm64/configs/gki_defconfig
        
        # 保持原始sed替换命令
        sed -i 's/res="\$res\$(cat "\$file")"/res="${{ inputs.KERNEL_NAME }}"/g' common/scripts/setlocalversion

    # 保留原始编译步骤
    - name: Build kernel
      working-directory: $KERNEL_DIR/kernel_platform
      run: |
        tools/bazel run --config=fast //common:kernel_aarch64_dist -- --dist_dir=dist

    # 恢复原始AnyKernel3打包流程
    - name: Package kernel
      working-directory: $KERNEL_DIR/kernel_platform/dist
      run: |
        aria2c https://github.com/ShirkNeko/SukiSU_KernelPatch_patch/releases/download/0.11-beta/patch_linux
        chmod +x patch_linux
        ./patch_linux
        mv oImage Image
        
        git clone https://github.com/JiuGeFaCai/AnyKernel3.git
        cp Image AnyKernel3/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: OnePlus13_Kernel_${{ env.KSUVER }}
        path: $KERNEL_DIR/kernel_platform/dist/AnyKernel3/*
